In [1]:
!pip install tensorflow

     -------------------------------------- 276.6/276.6 MB 1.5 MB/s eta 0:00:00
     -------------------------------------- 126.5/126.5 kB 1.8 MB/s eta 0:00:00
  Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
  Using cached gast-0.4.0-py3-none-any.whl (9.8 kB)
  Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
     ---------------------------------------- 2.7/2.7 MB 2.6 MB/s eta 0:00:00
     ---------------------------------------- 24.4/24.4 MB 2.4 MB/s eta 0:00:00
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
     -------------------------------------- 422.5/422.5 kB 2.4 MB/s eta 0:00:00
     ---------------------------------------- 4.2/4.2 MB 2.8 MB/s eta 0:00:00
     ---------------------------------------- 5.6/5.6 MB 2.3 MB/s eta 0:00:00
     -------------------------------------- 440.8/440.8 kB 3.9 MB/s eta 0:00:00
     ---------------------------------------- 1.7/1.7 MB 2.5 MB/s eta 0:00:00
     ---------------------------------------- 1.5/1.5 MB 2.


[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
import tensorflow as tf

In [2]:
# Part 1: Theoretical Queltionk

# Q1. What are the different data structures used in Tensorflow?. Give some examples.
"""Ans: The different data structures used in Tensorflow are: """
    # 1. Tensors: Tensors are the fundamental building blocks of TensorFlow, and they represent multi-dimensional arrays of data.
    # Example:   
vector = tf.constant([1, 2, 3, 4, 5])
print(vector)   
    # 2. Variables: Variables are mutable tensors used to store model parameters during training. 
    # Example:
weights = tf.Variable(tf.random.normal(shape=(2, 5)))
print(weights)
    # 3.SparseTensor: A SparseTensor is a special data structure used for sparse data, where most of the elements are zero. 
    # Example: 
indices = tf.constant([[0, 0], [1, 1], [2, 3]], dtype=tf.int64)
values = tf.constant([1, 2, 3], dtype=tf.int64)
shape = tf.constant([3, 4], dtype=tf.int64)
sparse_tensor = tf.SparseTensor(indices, values, shape)
print(sparse_tensor)

    # 4. RaggedTensor: RaggedTensor is used to represent sequences of varying lengths efficiently. 
    # Example: 
rt = tf.ragged.constant([[1, 2], [3], [4, 5, 6]])
print(rt)




# Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
    # Ans: TensorFlow Constant:
        # A constant in TensorFlow is an immutable data structure. 
        # It is mainly used to hold fixed values that remain the same throughout the computation.
        # Constants are typically used for model hyperparameters, input data, or any other values that do not change during the training process.
        # When you define a constant, its value is fixed, and you cannot update it later during the execution of your TensorFlow graph.
a = tf.constant(5)
b = tf.constant([1, 2, 3])
print(a)
print(b)

    # Ans: TensorFlow Variable:
        # A variable in TensorFlow is a mutable data structure. 
        # It can be updated during the execution of the TensorFlow graph.
        # Variables are commonly used to represent the learnable parameters of a machine learning model (e.g., weights and biases). 
        # During training, the values of these variables are updated based on the optimization algorithm to minimize the loss function.
        # Variables are defined with an initial value and can be modified using assignment operations.
weights = tf.Variable(tf.random.normal(shape=(5, 2)))
new_weights = weights * 2
weights.assign(new_weights)
print(weights)





# Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
    # Ans: Matrix Addition:
        # Matrix addition is performed element-wise on two matrices of the same shape, resulting in a new matrix with the same shape.
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])
C = tf.add(A, B)
print(C)
     # Matrix Multiplication:
        # Matrix multiplication is a binary operation that takes two matrices and produces a new matrix by performing a combination 
        # of dot products between rows and columns of the input matrices.
C = tf.matmul(A, B)
print(C)
    # Element-wise Operations:
        # Element-wise operations are performed independently on each element of the input tensors, without considering their 
        # shapes or dimensions. 
C_add = tf.add(A, B)
C_multiply = tf.multiply(A, B)
print(C_add)
print(C_multiply)



tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
<tf.Variable 'Variable:0' shape=(2, 5) dtype=float32, numpy=
array([[ 0.46474242, -1.0578883 ,  0.95636547, -0.33751684,  0.6998484 ],
       [-0.01589162,  0.00275547, -0.48423976,  1.5965444 ,  0.46902624]],
      dtype=float32)>
SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 1]
 [2 3]], shape=(3, 2), dtype=int64), values=tf.Tensor([1 2 3], shape=(3,), dtype=int64), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))
<tf.RaggedTensor [[1, 2], [3], [4, 5, 6]]>
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(5, 2) dtype=float32, numpy=
array([[ 0.7565864 , -1.0312902 ],
       [ 0.09221864, -0.73170036],
       [-0.72737813,  5.3129215 ],
       [ 0.94913924, -2.508074  ],
       [ 1.6361765 , -2.7959406 ]], dtype=float32)>
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(

In [13]:
# Part 2: Practical Implementation

# Task 1: Creating and Manipulating Matrice
# Q1. Create a normal matrix A with dimensions 2x2, using TensorFlow's random_normal function. Display the values of matrix A.
A = tf.random.normal(shape=(2, 2))
print(A)

# Q2. Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Display the values of matrix B.
B = tf.random.truncated_normal(shape=(2, 2))
print(B)

# Q3. Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with a mean of 2 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.
C = tf.random.normal(shape=(2, 2), mean = 3, stddev = 0.5)
print(C)

# Q4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
D = tf.add(A, B)
print(D)

# Q5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
E = tf.matmul(C, D)
print(E)


tf.Tensor(
[[ 1.0981367  -1.5833466 ]
 [ 0.97178334  1.4424926 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.2941861  -0.6237941 ]
 [ 0.85712296 -0.09958952]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[2.1544585 3.6808467]
 [3.3366928 3.0316503]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.3923228 -2.2071407]
 [ 1.8289063  1.3429031]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[11.886084    0.18782733]
 [13.527051   -3.2933378 ]], shape=(2, 2), dtype=float32)


In [16]:
# Task 2: Performing Additional Matrix Operations
# Q1. Create a matrix F with dimensions 2x2, initialized with random values using TensorFlow's random_uniform function.
F = tf.random.uniform(shape=(3, 3))
print(F)

# Q2. Calculate the transpose of matrix F and store the result in matrix G.
G = tf.transpose(F)
print(G)

# Q3. Calculate the element-wise exponential of matrix F and store the result in matrix H.
H = tf.math.exp(F)
print(H)

# Q4. Create a matrix I by concatenating matrix F and matrix G horizontally.
I = tf.concat((F, G), axis = 1)
print(I)

# Q5. Create a matrix J by concatenating matrix F and matrix H vertically.
J = tf.concat((F, H), axis = 0)
print(J)

tf.Tensor(
[[0.25272083 0.05475414 0.1675334 ]
 [0.07976854 0.25603318 0.30851996]
 [0.62436914 0.8814589  0.4798329 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.25272083 0.07976854 0.62436914]
 [0.05475414 0.25603318 0.8814589 ]
 [0.1675334  0.30851996 0.4798329 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1.2875237 1.0562809 1.1823847]
 [1.0830363 1.2917956 1.3614087]
 [1.8670677 2.4144194 1.6158043]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.25272083 0.05475414 0.1675334  0.25272083 0.07976854 0.62436914]
 [0.07976854 0.25603318 0.30851996 0.05475414 0.25603318 0.8814589 ]
 [0.62436914 0.8814589  0.4798329  0.1675334  0.30851996 0.4798329 ]], shape=(3, 6), dtype=float32)
tf.Tensor(
[[0.25272083 0.05475414 0.1675334 ]
 [0.07976854 0.25603318 0.30851996]
 [0.62436914 0.8814589  0.4798329 ]
 [1.2875237  1.0562809  1.1823847 ]
 [1.0830363  1.2917956  1.3614087 ]
 [1.8670677  2.4144194  1.6158043 ]], shape=(6, 3), dtype=float32)
